apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base configuration
bases:
- ../../base

# Set the namespace for all resources
namespace: ${APP_NAME}

# Define images to replace
images:
- name: lamp-app
  newName: image-registry.openshift-image-registry.svc:5000/${APP_NAME}/lamp-app
  newTag: ${GIT_BRANCH}

# Set common labels for all resources
commonLabels:
  app.kubernetes.io/part-of: ${APP_NAME}
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/environment: ${APP_NAME}

# Apply patches to customize resources
patchesStrategicMerge:
- |-
  # Customize PHP deployment
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: lamp-app
  spec:
    replicas: ${PHP_REPLICAS}
    template:
      spec:
        containers:
        - name: lamp-app
          resources:
            limits:
              memory: "${PHP_MEMORY_LIMIT}"
              cpu: "${PHP_CPU_LIMIT}"
            requests:
              memory: "${PHP_MEMORY_REQUEST}"
              cpu: "${PHP_CPU_REQUEST}"
          # Adding only the env vars that don't conflict with valueFrom
          env:
          - name: APP_ENV
            value: "${APP_NAME}"

- |-
  # Customize MySQL deployment
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mysql
  spec:
    replicas: ${MYSQL_REPLICAS}
    template:
      spec:
        containers:
        - name: mysql
          resources:
            limits:
              memory: "${MYSQL_MEMORY_LIMIT}"
              cpu: "${MYSQL_CPU_LIMIT}"
            requests:
              memory: "${MYSQL_MEMORY_REQUEST}"
              cpu: "${MYSQL_CPU_REQUEST}"
          # No env vars here to avoid conflicts with valueFrom

# Create a replacement secret
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: mysql-secret
  type: Opaque
  stringData:
    username: "${MYSQL_USER}"
    password: "${MYSQL_PASSWORD}"
    database: "${MYSQL_DATABASE}"
    root-password: "${MYSQL_ROOT_PASSWORD}"

- |-
  # Customize PVC for MySQL if storage class is specified
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mysql-pvc
  spec:
    storageClassName: "${MYSQL_STORAGE_CLASS}"

# Add ConfigMap with application configuration
configMapGenerator:
- name: ${APP_NAME}-config
  literals:
  - GIT_REPOSITORY_URL=${GIT_REPOSITORY_URL}
  - GIT_BRANCH=${GIT_BRANCH}
  - APP_NAME=${APP_NAME}
  - INIT_DATABASE=${INIT_DATABASE}