apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base configuration
bases:
- ../../base

# Set the namespace for all resources
namespace: lamp-prod

# Apply patches to the base resources
patchesStrategicMerge:
- |-
  # Patch for production environment settings
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: lamp-app
  spec:
    replicas: 3  # Multiple replicas for high availability
    template:
      spec:
        containers:
        - name: lamp-app
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

# Add common labels to all resources
commonLabels:
  environment: prod