apiVersion: v1
kind: ConfigMap
metadata:
  name: lamp-config
  labels:
    app: lamp-app
data:
  # Application configuration key-value pairs
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_NAME: "${APP_NAME}"
  GIT_REPOSITORY_URL: "${GIT_REPOSITORY_URL}"
  GIT_BRANCH: "${GIT_BRANCH}"