apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce  # RWO is the most widely supported access mode
  resources:
    requests:
      storage: 1Gi  # Adjust size based on your needs
  storageClassName: gp2-csi  # Update to match your cluster's storage class