apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Use the storageClassName from environment variable, or default if not provided
  # The placeholder will be replaced during deployment
  storageClassName: ${MYSQL_STORAGE_CLASS}