# Updated mysql-deployment.yaml with fixed readiness probe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1  # MySQL typically runs as a single instance or in a cluster configuration
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate  # Ensures we don't have multiple MySQL instances trying to use the same PVC
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        # Environment variables for MySQL configuration
        env:
        - name: MYSQL_ROOT_PASSWORD  # Root password (required)
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE  # Database to create on startup
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        - name: MYSQL_USER  # Non-root user to create
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD  # Password for non-root user
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        # Mount the persistent storage
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        # Resource requests and limits
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        # Health checks - UPDATED PROBES
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc  # Must match PVC name