apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  # These are example values, replace with actual secure passwords in production
  username: lamp_user
  password: lamp_password
  database: lamp_db
  root-password: root_password