apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  storageClassName: "gp3-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi