apiVersion: v1
kind: ConfigMap
metadata:
  name: git-repo-config
  namespace: lamp-dev
data:
  GIT_REPOSITORY_URL: "https://github.com/rh-joanders/msu.git"

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: lamp-git-push-binding
  namespace: lamp-dev
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.after)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: branch-name
    value: $(body.ref.split('/')[2])