apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: lamp-pipeline-run-
  namespace: lamp-dev
spec:
  pipelineRef:
    name: lamp-pipeline
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: pipeline-workspace-pvc
  params:
  - name: git-url
    value: ${GIT_REPOSITORY_URL}
  - name: git-revision
    value: ${GIT_BRANCH}
  - name: image-name
    value: lamp-app
  - name: image-tag
    value: ${IMAGE_TAG}
  - name: deployment-path
    value: manifests/overlays/${APP_NAME}/kustomization.yaml
  - name: app-name
    value: ${APP_NAME}
  - name: deployment-namespace
    value: ${APP_NAME}