apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lamp-pipeline
spec:
  description: |
    This pipeline clones the LAMP application repository, builds the container image,
    updates the Kubernetes manifests, and triggers ArgoCD to sync the application.
  workspaces:
  - name: shared-workspace  # Workspace for sharing data between tasks
  params:
  - name: git-url
    type: string
    description: URL of the git repo
  - name: git-revision
    type: string
    description: Git revision to build
    default: main
  - name: image-name
    type: string
    description: Name of the image to build
  - name: image-tag
    type: string
    description: Tag of the image to build
  - name: add-latest-tag
    type: string
    description: Additional tag (latest) for the image
    default: ""
  - name: deployment-path
    type: string
    description: Path to the kustomization.yaml file to update
  - name: app-name
    type: string
    description: Name of the ArgoCD application to sync
  tasks:
  # Task 1: Clone the git repository
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: Task
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"

  # Task 2: Build and push the container image
  - name: build-image
    taskRef:
      name: buildah
      kind: Task
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.image-name):$(params.image-tag)
    - name: CONTEXT
      value: application
    - name: DOCKERFILE
      value: Dockerfile
    - name: ADDITIONAL_TAGS
      value: $(params.add-latest-tag)

  # Task 3: Update the deployment manifests with the new image
  - name: update-manifests
    taskRef:
      name: update-deployment
      kind: Task
    runAfter:
    - build-image
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: image-name
      value: $(params.image-name)
    - name: image-tag
      value: $(params.image-tag)
    - name: deployment-path
      value: $(params.deployment-path)

  # Task 4: Trigger ArgoCD to sync the application
  - name: sync-application
    taskRef:
      name: argocd-task-sync-and-wait
      kind: Task
    runAfter:
    - update-manifests
    params:
    - name: application-name
      value: $(params.app-name)
    - name: flags
      value: --insecure