apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
  namespace: ${NAMESPACE}
  labels:
    app: argocd-pipeline-credentials
    argocd.argoproj.io/managed-by: manual
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  ARGOCD_USERNAME: "admin"
  ARGOCD_PASSWORD: "${ARGOCD_PASSWORD}"