apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-argocd-access-${APP_NAME}
  namespace: openshift-gitops
  labels:
    app: pipeline
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-argocd-access-${APP_NAME}