apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-argocd-access-${APP_NAME}
  namespace: openshift-gitops
  labels:
    app: pipeline
rules:
- apiGroups: ["argoproj.io"]
  resources: ["applications"]
  verbs: ["get", "list", "watch", "update", "patch", "sync"]
- apiGroups: ["argoproj.io"]
  resources: ["appprojects"]
  verbs: ["get", "list", "watch"]