apiVersion: argoproj.io/v1beta1
kind: ApplicationSet
metadata:
  name: lamp-environments
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - name: lamp-dev
        namespace: lamp-dev
        path: manifests/overlays/lamp-dev
        branch: main
      - name: lamp-prod
        namespace: lamp-prod
        path: manifests/overlays/lamp-prod
        branch: prod
  template:
    metadata:
      name: '{{name}}'
      namespace: openshift-gitops
      labels:
        environment: '{{name}}'
    spec:
      project: default
      source:
        repoURL: ${GIT_REPOSITORY_URL}
        targetRevision: '{{branch}}'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

---
# This ApplicationSet dynamically creates ArgoCD applications for feature branches
apiVersion: argoproj.io/v1beta1
kind: ApplicationSet
metadata:
  name: lamp-feature-branches
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: ${GIT_REPOSITORY_URL}
      revision: HEAD
      directories:
      - path: manifests/overlays/lamp-feature-*
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        environment: feature
    spec:
      project: default
      source:
        repoURL: ${GIT_REPOSITORY_URL}
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true