apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lamp-dev
  namespace: openshift-gitops
  labels:
    environment: dev
spec:
  project: default
  source:
    repoURL: ${GIT_REPOSITORY_URL}
    targetRevision: main
    path: manifests/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lamp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lamp-prod
  namespace: openshift-gitops
  labels:
    environment: prod
spec:
  project: default
  source:
    repoURL: ${GIT_REPOSITORY_URL}
    targetRevision: prod
    path: manifests/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lamp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
# This is an ApplicationSet that will dynamically create ArgoCD applications for feature branches
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lamp-feature-branches
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: ${GIT_REPOSITORY_URL}
      revision: HEAD
      directories:
      - path: manifests/overlays/lamp-feature-*
  template:
    metadata:
      name: 'lamp-{{path.basename}}'
      labels:
        environment: feature
    spec:
      project: default
      source:
        repoURL: ${GIT_REPOSITORY_URL}
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true