# gitops/application-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lamp-dev
  namespace: openshift-gitops
  labels:
    environment: dev
spec:
  project: default
  source:
    repoURL: ${GIT_REPOSITORY_URL}
    targetRevision: main
    path: manifests/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lamp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lamp-prod
  namespace: openshift-gitops
  labels:
    environment: prod
spec:
  project: default
  source:
    repoURL: ${GIT_REPOSITORY_URL}
    targetRevision: prod
    path: manifests/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lamp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true