apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
  labels:
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/part-of: lamp-stack
spec:
  project: default
  source:
    repoURL: ${GIT_REPOSITORY_URL}
    targetRevision: HEAD
    path: manifests/overlays/${APP_NAME}
    # Fixed kustomize section
    kustomize:
      images:
        - "image-registry.openshift-image-registry.svc:5000/${APP_NAME}/lamp-app:${IMAGE_TAG}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ${APP_NAME}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true